Feat/projectspecific s3
it-at-m/digiwf-email-integration pull request #25
Opened 2022-10-05 14:00 UTC by lmoesle

---
name: Pull request
about: Contribute your changes to the project
title: '[pull-request]'
labels: ''
assignees: ''
---
**Description**
Short description or comments

**Reference**
Issues #XXX

**Checklist**

- [ ] Acceptance criteria are met
- [ ] Pipeline has been run successfully
- [ ] JUnit tests have been run successfully
- [ ] Changelog is adjusted
- [ ] [Documentations](https://git.muenchen.de/groups/digitalisierung/-/wikis/Dokumentationen) are completed
- [ ] Frontend is tested
- [ ] Created sub-branches are deleted
- [ ] Boards are updated ( [Digitalisierung](https://git.muenchen.de/groups/digitalisierung/-/boards) , [Support](https://git.muenchen.de/digitalisierung/digiwf-support) , [Zenhub](https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/board) )
- [ ] feature process is created or extended
- [ ] [git-ops](https://git.muenchen.de/digitalisierung/digiwf-ops) is customized
- [ ] Openshift environments are prepared (Secrets, etc.)

2022-10-16 16:10 UTC, dominikhorn93 commented on digiwf-email-integration-starter/pom.xml
> -        <version>0.0.2</version>
0.1.0

2022-10-16 16:15 UTC, dominikhorn93 requested changes
Super Job 👍 

Wollen wir ein Issue machen, um es ins monorepo zu migrieren?

2022-10-16 16:15 UTC, dominikhorn93 commented on digiwf-email-integration-service/pom.xml
> -        <version>0.0.2</version>
0.1.0

2022-10-16 16:15 UTC, dominikhorn93 commented on digiwf-email-integration/src/main/java/io/muenchendigital/digiwf/email/integration/domain/service/MailingService.java
>  @AllArgsConstructor
@Validated

2022-10-16 16:15 UTC, dominikhorn93 commented on digiwf-email-integration/src/main/java/io/muenchendigital/digiwf/email/integration/domain/service/MailingService.java
> +    public void sendMail(final Mail mail) throws RuntimeException {
@Valid Mail mail

2022-10-16 16:15 UTC, dominikhorn93 commented on digiwf-email-integration/src/main/java/io/muenchendigital/digiwf/email/integration/domain/service/MailingService.java
> +        final Validator validator = this.validatorFactory.getValidator();
kannst du weglassen, wenn du `@Validated` und `@Valid` machst.

2022-10-16 16:15 UTC, dominikhorn93 commented on docs/sendMail.json
> +        "type": "camunda:inputParameter",
warum inputParameter? ist doch für eine CallActivity oder?

2022-10-16 16:15 UTC, dominikhorn93 commented on example-digiwf-email-integration/pom.xml
> -        <version>0.0.2</version>
0.1.0

2022-10-17 05:27 UTC, lmoesle commented
> Super Job +1
> 
> Wollen wir ein Issue machen, um es ins monorepo zu migrieren?

@dominikhorn93 Danke für die Review 😃 

Eine Issue bzw. Epic habe ich schon erstellt. Ich bereite das für das Planning noch ein wenig auf.
https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-project/356

2022-10-17 07:29 UTC, darenegade commented on digiwf-email-integration-service/src/main/resources/application-local.properties
> +#spring.cloud.stream.kafka.binder.brokers=dwf-cluster-kafka-tls-bootstrap-lhmeventbus.apps.capk.muenchen.de:443
This is lhm specific and should be removed

2022-10-17 07:30 UTC, darenegade commented on digiwf-email-integration-service/src/main/resources/application-local.properties
> +#spring.cloud.stream.kafka.binder.brokers=dwf-cluster-kafka-tls-bootstrap-lhmeventbus.apps.capk.muenchen.de:443
Other lines within this properties files are specific too

2022-10-17 07:31 UTC, darenegade commented on digiwf-email-integration/src/main/java/io/muenchendigital/digiwf/email/integration/domain/service/MailingService.java
> +import javax.validation.*;
Wild card imports should be avoided

2022-10-17 07:33 UTC, darenegade commented on example-digiwf-email-integration/src/main/resources/application-local.properties
> +io.muenchendigital.digiwf.mail.fromAddress=itm.digitalwf-test@muenchen.de
Remove lhm specific prop values

2022-10-18 16:27 UTC, dominikhorn93 requested changes

2022-10-18 16:27 UTC, dominikhorn93 commented on docs/sendMail.json
> -        "type": "camunda:in",
Da gilt doch für alle Inputs oder?
Verstehe nicht warum die auf inputParameter sind. 
Dadurch landen die ja nicht im StreamingTemplate oder verstehe ich das gerade falsch?

2022-10-18 16:28 UTC, dominikhorn93 approved these changes, later dismissed

2022-10-19 13:21 UTC, dominikhorn93 approved these changes

2022-10-19 14:34 UTC, merged